version: "3.5"

services: 
  docker:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports: 
      - 2376:2376
    networks: 
      - jenkins
  
  jenkins:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports: 
      - 8080:8080
      - 50000:50000
    networks: 
      - jenkins
    
volumes:
  jenkins-docker-certs:
  jenkins-data:

networks: 
  jenkins: